#!/bin/bash
SERVICE_NAME="app"
export CURRENT_UID=$(id -u):$(id -g)

alias dc="docker-compose"
alias build="dc build && dr npm install"
alias down="dc down"
alias up="down && dc up"
alias dr="dc run \$SERVICE_NAME"
alias test="dr npm run test:unit"
alias tst="test"