version: "3.7"
services:
  app:
    build: .
    user: ${CURRENT_UID}
    environment:
      - TZ='America/Recife'
    working_dir: /app/
    volumes:
      - ./app/:/app/
    command: "npm run serve"
    ports:
      - 8080:8080